# Generated by Django 4.0 on 2022-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_coordinates', models.CharField(max_length=120)),
                ('input_frame', models.CharField(choices=[('icrs', 'ICRS'), ('fk5', 'FK5'), ('fk4', 'FK4'), ('galactic', 'Galactic')], default='icrs', max_length=20)),
                ('input_units', models.CharField(choices=[('hmsdms', 'hmsdms'), ('deg', 'deg')], default='hmsdms', max_length=10)),
                ('gal_b', models.FloatField(blank=True, null=True)),
                ('gal_l', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
