# Generated by Django 3.2.8 on 2021-12-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='uploads')),
                ('test', models.CharField(max_length=120)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
