# Generated by Django 4.0 on 2022-02-13 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.FileField(default='', upload_to='working')),
                ('name', models.CharField(max_length=45, null=True)),
                ('frequency', models.FloatField(null=True)),
                ('units', models.CharField(choices=[('jy_beam', 'Jy per beam')], max_length=25, null=True)),
                ('naxis3', models.IntegerField(null=True)),
                ('naxis4', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(default='', upload_to='uploads')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('telescope', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_size', models.FloatField(null=True)),
                ('parsed_header', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FFHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_header', models.JSONField()),
                ('fits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.ff')),
            ],
        ),
        migrations.CreateModel(
            name='FFFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('x3', models.FloatField()),
                ('y3', models.FloatField()),
                ('fits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.ff')),
            ],
        ),
        migrations.AddField(
            model_name='ff',
            name='file_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.ffupload'),
        ),
    ]
