# Generated by Django 4.0 on 2022-02-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_ffupload_parsed_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffupload',
            name='file_hash',
            field=models.CharField(max_length=43, null=True, unique=True),
        ),
    ]
