# Generated by Django 4.0 on 2022-02-13 05:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_ffupload_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fffootprint',
            name='x0',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='x3',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='y0',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='y2',
        ),
        migrations.RemoveField(
            model_name='fffootprint',
            name='y3',
        ),
        migrations.AddField(
            model_name='fffootprint',
            name='footprint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[1, 2], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ff',
            name='name',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
