# Generated by Django 4.0 on 2022-02-13 10:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0005_alter_fffootprint_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ff',
            name='footprint',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), default=[1, 2, 3], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FFFootprint',
        ),
    ]
