# Generated by Django 4.0 on 2022-02-13 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_ff_footprint_delete_fffootprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ff',
            name='center_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ff',
            name='center_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ff',
            name='radius',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ff',
            name='footprint',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
